I manage to make a payment
Momezz/backend-hotel-booking pull request #15
Opened 2023-01-12 16:21 UTC by Momezz

### Descripción
[//]: <> (Aca debe ir la descripcion del PullRequest, que es? que hace?)
changes are made to implement payments with stripe
**Probar con la rama del front feature/HB-13-payment-booking**

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [x] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)
[HB-13](https://dcquinche.atlassian.net/jira/software/projects/HB/boards/2/backlog?selectedIssue=HB-13)
### Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)

### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2023-01-13 00:24 UTC, NishiNegi commented on app.js
> +const dotenv = require('dotenv');
¿Cuál es el objetivo de este archivo? Veo que varias de las funciones tienen el mismo objetivo que las que tenemos en src/index.ts

2023-01-13 00:27 UTC, NishiNegi commented on src/api/healthcheck/healthcheck.controller.js
> +const dotenv = require('dotenv');
¿Por qué este archivo se creo con JS y no con TS?

También recuerda que la función general del healthcheck es solamente probar y demostrar que el servidor esta corriendo. Nada más. En esta carpeta no debería haber nada de Stripe.

2023-01-13 00:27 UTC, NishiNegi commented on src/api/healthcheck/index.ts
> -import { Router, Request, Response } from 'express';
recuerda que la función general del healthcheck es solamente probar y demostrar que el servidor esta corriendo. Nada más. En esta carpeta no debería haber nada de Stripe.

2023-01-13 00:29 UTC, NishiNegi commented on src/api/payment/payment.controller.ts
> +  console.log(req.body);
Recuerda no dejar console.log por ahí sueltos.

2023-01-13 00:30 UTC, NishiNegi requested changes
Por favor revisa mis comentarios en el código. Hay varias cosas que tal vez no están bien ubicadas o que no veo su funcionalidad.

2023-01-14 13:07 UTC, khriztianmoreno requested changes
@Momezz por favor corregir los cambios solicitados antes del medio dia del sabado, no se puede esperar mas para tener esto listo

2023-01-14 13:07 UTC, khriztianmoreno commented on app.js
> +const dotenv = require('dotenv');
@Momezz este archivo no es necesario, ya tienes el `index.ts`  que hace lo mismo, ademas esta en `.js` eso me da a entender que fue un copy/paste.

Por favor borralo y ajusta los cambios q @NishiNegi  te sugirio.

2023-01-14 13:07 UTC, khriztianmoreno commented on src/api/healthcheck/healthcheck.controller.js
> +const dotenv = require('dotenv');
@Momezz nuevamente un archivo `.js` todo parece inidicar q copiaste, ademas este controllador no debe llevar la funcionalidad de pagos

2023-01-14 13:07 UTC, khriztianmoreno commented on src/api/healthcheck/healthcheck.controller.js
> +      description: 'Pago de prueba top-v25 equipo 2',
Este valor no debe ser hardcodeado, debe ser el servicio que adquirieron, 

Ejemplo: hotel xx, apt yy

2023-01-14 13:07 UTC, khriztianmoreno commented on src/api/healthcheck/index.ts
> +router.post('/', handlerHealthcheck);
Esto no es necesario, debes dejar el archivo tal cual esta. la responsabilidad de este endpoint es `demostrar que el servidor esta corriendo`

2023-01-14 13:07 UTC, khriztianmoreno commented on src/api/payment/payment.controller.ts
> +  console.log(req.body);
Remueve el console.log

```suggestion
```

2023-01-18 21:52 UTC, dcquinche approved these changes
Working fine.

2023-01-19 20:59 UTC, juanor9 approved these changes

2023-01-19 21:01 UTC, merged